name: Trigger update to oc.pulse.18.04 and oc.user

on:
  push:
    branches: [main]

jobs:
  trigger:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch repository oc.pulse.18.04
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.pulseaudio.18.04
          event-type: dispatch-from-pulse

      - name: Dispatch oc.user repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user
          event-type: dispatch-from-pulse
